### ISSUE TITLE
"python3 setup.py install" fails

### ISSUE THREAD

**Issue by felixheld** [enjoy-digital/litevideo#12]
The installation of the module in the virtualenv fails and generates this warning:
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

Running "python3 setup.py develop" works though.

**Comment by enjoy-digital** [comment]
thanks, fixed via https://github.com/enjoy-digital/litevideo/commit/091c9ecdec8f5a7b92a85d3fab0edd7efcac5fb1.
