### ISSUE TITLE
clock_cls?

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litevideo#23]
it seems that the following line limits the use of the litevideo for only XC6 XC7 FPGA's?

self.submodules.clocking = clocking_cls[family](pads, external_clocking)

**Comment by enjoy-digital** [comment]
Indeed, the others FPGA families are not currently supported.

**Comment by enjoy-digital** [comment]
Closing since that's the only supported FPGA families (for now) and specified in the README.
