### ISSUE TITLE
Got this working on de10nano with MiSTer I/O board via vga

### ISSUE THREAD

**Issue by rob-ng15** [enjoy-digital/litevideo#33]
Had to change the initiator slightly...

`        # VGA terminal
        self.mem_map["terminal"] = 0x30000000
        self.submodules.terminal = terminal = Terminal()
        self.add_wb_slave(self.mem_map["terminal"], self.terminal.bus, 8896)
        self.add_memory_region("terminal", self.mem_map["terminal"], 8896, type="cached+linker")        

        # Connect VGA pins
        vga = platform.request("vga", 0)
        self.comb += [
            vga.vsync.eq(terminal.vsync),
            vga.hsync.eq(terminal.hsync),
            vga.red.eq(terminal.red[2:8]),
            vga.green.eq(terminal.green[2:8]),
            vga.blue.eq(terminal.blue[2:8])
        ]
        vga.en.eq(1)
`

![IMG_20200607_142946](https://user-images.githubusercontent.com/58272847/83972461-25467c00-a8d8-11ea-86d9-634204e03a63.jpg)

Relevent pins from the de10nano platform file...

`    ("vga", 0,
        Subsignal("red", Pins("AE17 AE20 AF20 AH18 AH19 AF21")),
        Subsignal("green", Pins("AE19 AG15 AF18 AG18 AG19 AG20")),
        Subsignal("blue", Pins("AG21 AA20 AE22 AF22 AH23 AH21")),
        Subsignal("hsync", Pins("AH22")),
        Subsignal("vsync",  Pins("AG24")),
        Subsignal("en",  Pins("AH27")),
        IOStandard("3.3-V LVTTL")
    ),
`

**Comment by enjoy-digital** [comment]
Thanks for the feedback, i'll have a closer look at the changes and will apply them. Do you want to create a PR to `litex-boards` to add the VGA pins to the de0nano?

**Comment by rob-ng15** [comment]
Will do.

**Comment by rob-ng15** [comment]
Have tidied things up a bit and submitted a pull request.

Controversial thing may be switching the uart to the mister i/o board rather than via the arduino pins, but have left that option in, but commented out.

**Comment by rob-ng15** [comment]
By the way, was for de10nano with MiSTer i/o board.
